require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'schoolferry' do

  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])


  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  target 'schoolferryTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'schoolferry-tvOS' do
  # Pods for schoolferry-tvOS

  target 'schoolferry-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
